version: '3'

services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
    depends_on:
      - 'cloudflared'
    environment:
      - TZ='America/Los Angeles'
      - PIHOLE_DNS_=192.168.10.10#5053
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/sndmasq.d
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: '192.168.10.11'

  cloudflared:
    image: visibilityspots/cloudflared:latest
    container_name: cloudflared
    ports:
      - 5053:5053/udp
      - 5053:5053/tcp
      - 49312:49312/tcp
    environment:
      - TZ='America/Los Angeles'
      - TUNNEL_DNS_UPSTREAM='https://1.1.1.1/dns-query,https://1.0.0.1/dns-query'
      - PORT=5053
      - ADDRESS=0.0.0.0
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: '192.168.10.10'

  speedtest:
    image: openspeedtest/latest:latest
    container_name: openspeedtest
    ports:
      - '3000:3000/tcp'
      - '3001:3001/tcp'
    restart: unless-stopped
    networks:
      pihole_network:
        ipv4_address: '192.168.10.12'

networks:
  pihole_network:
    ipam:
      driver: default
      config:
        - subnet: '192.168.10.0/24'
